title: Temple Five Dawns
description: >- # this means to ignore newlines until "baseurl:"
  Данный репозиторий представляет собой полный архив ресурсов,
  стратегических документов и медиа-материалов русскоязычного Discord-сообщества
  "Храм Пяти Рассветов" — официального сообщества для игроков класса монах в игре World of Warcraft.
baseurl: "/temple-five-dawns"
url: "https://alexzedim.github.io"
github: alexzedim
theme: jek

contact: true
about: true

# Указываем, что markdown-файлы лежат в messages
collections:
  messages:
    output: true
    permalink: /:collection/:path/

# Включаем все файлы из messages
include:
  - messages

edit-date: false # show the date of last edit on pages
default-theme: sandcastle # pick which theme loads by default

# Опционально: если нужны плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
